ring_den_andra_gpun_och_be_den_sortera_datan_tack_puss:
	gcc bitonic.c milli.c CLutilities.c -lm -lOpenCL -I/usr/local/cuda/include -o bitonic_cl
	./bitonic_cl

ring_den_andra_gpun:
	gcc find_max.c milli.c CLutilities.c -lm -lOpenCL -I/usr/local/cuda/include -o find_max_cl
	./find_max_cl

ring_den_andra_gpun_och_sag_hej:
	gcc hello_world_cl.c CLutilities.c -lOpenCL -I/usr/local/cuda/include -o hello_world_cl

